# thomasvs: binary sensors
# Example configuration.yaml entry
- platform: template
  sensors:
    main_bedroom_ac:
      friendly_name: "Main Bedroom AC"
      device_class: power
      value_template: >-
        {{ states('sensor.power_neo_main_bedroom_ac_power')|float > 0 }}
    guest_bedroom_ac:
      friendly_name: "Guest Bedroom AC"
      device_class: power
      value_template: >-
        {{ states('sensor.power_neo_guest_bedroom_ac_power')|float > 0 }}
    main_bedroom_window:
      friendly_name: "Main Bedroom Window"
      device_class: window
      value_template: >-
        {{ is_state("sensor.sensor_hank_mber_window", "22") }}
# thomasvs: door sensors
    door_mber:
      friendly_name: "Main Bedroom Door"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_main_bedroom_alarm_level", "0") }}
    door_mber_closet:
      friendly_name: "Main Bedroom Door Closet"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_main_bedroom_closet_alarm_level", "0") }}
    door_gber:
      friendly_name: "Guest Bedroom Door"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_guest_bedroom_alarm_level", "0") }}
    door_gber_closet:
      friendly_name: "Guest Bedroom Door Closet"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_guest_bedroom_closet_alarm_level", "0") }}
    door_gbar:
      friendly_name: "Guest Bathroom Door"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_guest_bathroom_alarm_level", "0") }}
    door_hallway_closet:
      friendly_name: "Hallway Closet"
      device_class: door
      value_template: >-
        {{ not is_state("sensor.vision_door_hallway_closet_alarm_level", "0") }}
    main_bedroom_ac_blocked:
      friendly_name: "Main Bedroom AC Blocked"
      value_template: >-
        {% if is_state("binary_sensor.main_bedroom_window", "off") %}
          on
        {% else %}
          off
        {% endif %}
# thomasvs: moisture sensors
    herb_garden_left_moisture:
      friendly_name: "Herb Garden Left Moisture"
      device_class: "moisture"
      value_template: >-
        {{ is_state("sensor.leak_hs_ls100_herb_garden_left_flood", "2") }}
    herb_garden_right_moisture:
      friendly_name: "Herb Garden Right Moisture"
      device_class: "moisture"
      value_template: >-
        {{ is_state("sensor.leak_hs_ls100_herb_garden_right_flood", "2") }}
