homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  # Customization file
  customize: !include customize.yaml
  # thomasvs: allow packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# thomasvs: disabled
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# thomasvs: duckdns/ssl
http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:
# thomasvs
#   enable:
#     - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# thomasvs: split up config
group: !include groups.yaml
script: !include script.yaml
zone: !include zone.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
device_tracker: !include device_tracker.yaml
automation: !include_dir_merge_list automation/

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url

# thomasvs: zwave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  
# thomasvs: lights
# https://www.home-assistant.io/components/lifx/
# FIXME: might be no longer needed in config since 0.81
light:
 - platform: lifx
# thomasvs: light group
# see https://bonani.tech/three-different-approaches-for-grouping-light-entities-in-home-assistant/
 - platform: group
   name: Living Room Lights
   entities:
   - light.balcony
   - light.window_lights

 - platform: group
   name: Window Lights
   entities:
   - light.window_southest
   - light.window_south
   - light.window_north
   - light.window_northest

 - platform: group
   name: Grow Lights
   entities:
   - light.grow_kitchen
# thomasvs: turn wall switch into light
# see https://community.home-assistant.io/t/change-entity-from-light-device-to-switch-device/30164/5
 - platform: template
   lights:
     grow_kitchen:
       friendly_name: 'Grow Kitchen'
       level_template: '{{ 255 if is_state("switch.aeotec_zw096_grow_lights", "on") else 0 }}'
       value_template: '{{ is_state("switch.aeotec_zw096_grow_lights", "on") }}'
       turn_on:
         service: switch.turn_on
         entity_id: switch.aeotec_zw096_grow_lights
       turn_off:
         service: switch.turn_off
         entity_id: switch.aeotec_zw096_grow_lights
       set_level:
         service_template: switch.turn_{{ "off" if brightness == 0 else "on" }}
         entity_id: switch.aeotec_zw096_grow_lights

 - platform: template
   lights:
     kitchen_cabinet_backsplash:
       friendly_name: 'Kitchen Cabinet Backsplash'
       level_template: '{{ 255 if is_state("switch.hank_hkzwso01_smart_plug_switch", "on") else 0 }}'
       value_template: '{{ is_state("switch.hank_hkzwso01_smart_plug_switch", "on") }}'
       turn_on:
         service: switch.turn_on
         entity_id: switch.hank_hkzwso01_smart_plug_switch
       turn_off:
         service: switch.turn_off
         entity_id: switch.hank_hkzwso01_smart_plug_switch
       set_level:
         service_template: switch.turn_{{ "off" if brightness == 0 else "on" }}
         entity_id: switch.hank_hkzwso01_smart_plug_switch

 - platform: group
   name: Kitchen Lights
   entities:
   - light.kitchen_north
   - light.kitchen_south
   - light.kitchen_cabinet_backsplash

 - platform: group
   name: Main Bedroom Lights
   entities:
   - light.main_bedroom_north
   - light.main_bedroom_south

 - platform: group
   name: Main Bathroom Lights
   entities:
   - light.main_bathroom_bath
   - light.main_bathroom_toilet


 - platform: group
   name: Guest Bedroom Lights
   entities:
   - light.guest_bedroom_west
   - light.guest_bedroom_east

 - platform: group
   name: Guest Bathroom Lights
   entities:
   - light.guest_bathroom_door
   - light.guest_bathroom_center
   - light.guest_bathroom_shower

 - platform: group
   name: Hallway Lights
   entities:
   - light.hallway
   
# thomasvs: media players
media_player:
#  - platform: sonos
  - platform: plex
  - platform: epson
    host: 192.168.1.127
  - platform: onkyo
    host: 192.168.1.32
    name: receiver
    sources:
      pc: 'HTPC'
  - platform: samsungtv
    host: 192.168.1.20
    
# thomasvs: logger
# https://www.home-assistant.io/components/logger/
logger:
  default: info
  logs:
    homeassistant.core: debug
    # thomasvs: log zwave better
#   homeassistant.components.zwave: debug
#   homeassistant.components.light.zwave: debug
#   libopenzwave: debug
#   openzwave: debug

# thomasvs: google assistant integration
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  # exposed_domains:
  #  - switch
  #  - light
  #  - group
  entity_config:
    # switch.kitchen:
    #  name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
    #  aliases:
    #    - BRIGHT_LIGHTS
    #    - ENTRY_LIGHTS
    # light.living_room:
    #   expose: true
    #   room: Living Room
    light.grow_kitchen:
      expose: true
      room: Kitchen
    media_player.main_bedroom:
      expose: true
      room: Bedroom


# enable darksky weather for nice weather cards in lovelace
# See https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# humidifier
# fan:
#  - platform: xiaomi_miio
#    token: !secret xiaomi_humidifier_token
#    host: 192.168.1.120

# doorbird
doorbird:
  token: !secret doorbird_token
  devices: 
    - host: !secret doorbird_host
      username: !secret doorbird_username
      password: !secret doorbird_password

camera:
 - platform: doorbird

# thomasvs: keep database smaller by purging
recorder:
  purge_keep_days: 8

# thomasvs: hassio menu disappeared at some point.
# See https://community.home-assistant.io/t/hass-io-menu-disappeared/25110/8
hassio:
