#### TIME/DATE ##################################
- platform: time_date
  display_options:
      - 'time'
      - 'date'
- platform: worldclock
  time_zone: Etc/UTC
  name: 'UTC'
- platform: worldclock
  time_zone: America/New_York
  name: 'New York'
- platform: worldclock
  time_zone: Europe/Madrid
  name: 'Barcelona'
- platform: worldclock
  time_zone: Australia/Brisbane
  name: 'Brisbane'

# Weather prediction
- platform: yr
# thomasvs: added
  name: Weather tomorrow
  forecast: 24
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness
- platform: yr
  name: Weather in 6h
  forecast: 6
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness

- platform: yr
  name: Weather now
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness


# thomasvs: system monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use


# thomasvs: wireless tag sensors
- platform: wirelesstag
  monitored_conditions:
    temperature
