#### TIME/DATE ##################################
- platform: time_date
  display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'

# Weather prediction
- platform: weather_data
# thomasvs: added
  name: Weather tomorrow
  forecast: 24
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness
- platform: weather_data
  name: Weather in 6h
  forecast: 6
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness

- platform: weather_data
  name: Weather now
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - cloudiness


# thomasvs: wireless tag sensors
- platform: wirelesstag
  monitored_conditions:
    - temperature
    - humidity



# thomasvs: plant sensors
#- platform: mitemp_bt
  #  hci_interface:
#   - 0
# only use the external one close to the herbs, so the other one can be kept for ha
#   - 1
#  batt_entities: True
# whitelist:
#   # white ones
#   - '80:EA:CA:89:5F:D3'
#   - '80:EA:CA:89:63:04'
#   - '80:EA:CA:89:68:44'
#   - 'c4:7c:8d:6b:a5:1f'
#   # green ones
#   - '80:ea:ca:89:52:75'
#   - '80:ea:ca:89:56:bd'
#  mac: '80:EA:CA:89:5F:D3'
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery
#- platform: mitemp_bt
#  mac: '80:EA:CA:89:63:04'
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery
#- platform: mitemp_bt
#  mac: '80:EA:CA:89:68:44'
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery

# thomasvs: miflora sensors
# https://www.home-assistant.io/integrations/miflora/
# FIXME: thomasvs: deprecated in 2022.8.0
# - platform: miflora
#   mac: '80:ea:ca:89:52:75'
#   name: Parsley
#   force_update: true
#   go_unavailable_timeout: 43200
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery
# - platform: miflora
#   mac: '80:ea:ca:89:56:bd'
#   name: Rosemary
#   force_update: true
#   go_unavailable_timeout: 43200
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery
# - platform: miflora
#   name: herb3
#   mac: '80:EA:CA:89:5F:D3'
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery
# - platform: miflora
#   name: herb4
#   mac: '80:EA:CA:89:63:04'
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery
# - platform: miflora
#   name: herb5
#   mac: '80:EA:CA:89:68:44'
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery



