# thomasvs: flux light adjustment
# see https://www.home-assistant.io/components/switch.flux/
- platform: flux
  lights:
    - light.window_lights
#    - light.kitchen_lights
    - light.balcony_lights
  mode: xy
  start_colortemp: 5000
  sunset_colortemp: 4000
  stop_colortemp: 4000
