# thomasvs: flux light adjustment
# see https://www.home-assistant.io/components/switch.flux/
- platform: flux
  lights:
    - light.window_lights
    - light.kitchen_lights
    - light.balcony_lights
  mode: rgb
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2500
