# thomasvs: flux light adjustment
# see https://www.home-assistant.io/components/switch.flux/
- platform: flux
  lights:
    - light.window_lights
#    - light.kitchen_lights
    - light.balcony_lights
  mode: xy
  start_colortemp: 5000
  sunset_colortemp: 4000
  stop_colortemp: 4000

# thomasvs: smartir config
# thomasvs: removed for v2022.11
# - platform: broadlink
#   host: 192.168.1.139
#   mac: 'c8:f7:42:74:cb:78'
