- alias: Set Living TV Input
  trigger:
    platform: state
    entity_id: input_select.living_tv_input
  condition:
    - condition: template
      value_template: "{{ trigger.from_state is not none and trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: script.living_room_select_source
      data:
        source: "{{ trigger.to_state.state }}"

- alias: Set Bedroom TV Input
  trigger:
    platform: state
    entity_id: input_select.bedroom_tv_input
  action:
    service: rest_command.blackbird_switch
    data_template:
      output: 2
      input: >
            {% if is_state("input_select.bedroom_tv_input", "FIOS") %}
              1
            {%-elif is_state("input_select.bedroom_tv_input", "Stadia") %}
              2
            {%-elif is_state("input_select.bedroom_tv_input", "PS5") %}
              3
            {%-elif is_state("input_select.bedroom_tv_input", "PS4") %}
              4
            {% else %}
              none
            {% endif %}

- alias: Set Balcony Monitor Input
  trigger:
    platform: state
    entity_id: input_select.balcony_monitor_input
  action:
    service: rest_command.blackbird_switch
    data_template:
      output: 3
      input: >
            {% if is_state("input_select.balcony_monitor_input", "FIOS") %}
              1
            {%-elif is_state("input_select.balcony_monitor_input", "Stadia") %}
              2
            {%-elif is_state("input_select.balcony_monitor_input", "PS5") %}
              3
            {%-elif is_state("input_select.balcony_monitor_input", "PS4") %}
              4
            {% else %}
              none
            {% endif %}
