- alias: Main Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'sensor.main_bedroom_night_blinds'
    state: 'Closed'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_closed

- alias: Main Bedroom Blinds Partly
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'sensor.main_bedroom_night_blinds'
    state: 'Partly'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_partly

- alias: Guest Bedroom Close Blinds
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: script.turn_on
    entity_id:  script.guest_bedroom_close_blinds
- alias: Open Living Space Blinds on Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: scene.turn_on
    entity_id:
    - scene.balcony_open
    - scene.living_room_open
