- alias: Main Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'sensor.main_bedroom_night_blinds'
      state: 'Closed'
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Main Bedroom Blinds Partly
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'sensor.main_bedroom_night_blinds'
      state: 'Partly'
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_partly

# FIXME: add partly scene and automation
- alias: Guest Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
    - condition: state
      entity_id: 'sensor.guest_bedroom_night_blinds'
      state: 'Closed'
  action:
    service: script.turn_on
    entity_id:  script.guest_bedroom_close_blinds


- alias: Open Living Space Blinds 30 minutes before Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.show_the_sunset'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id:
    - scene.balcony_open
    - scene.living_room_open

#- alias: Living Space Blinds Closed at Night
#  trigger:
#    platform: template
#    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#  action:
#    service: scene.turn_on
#    entity_id:
#    - scene.balcony_blind
#    - scene.living_room_blind

- alias: Living Space Blinds Open in Morning
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.morning_blinds_open_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id:
    - scene.balcony_open
    - scene.living_room_open
