- alias: Main Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'sensor.main_bedroom_night_blinds'
      state: 'Closed'
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Main Bedroom Blinds Partly
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'sensor.main_bedroom_night_blinds'
      state: 'Partly'
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_partly

# FIXME: add partly scene and automation
- alias: Guest Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
    - condition: state
      entity_id: 'sensor.guest_bedroom_night_blinds'
      state: 'Closed'
  action:
    service: script.turn_on
    entity_id:  script.guest_bedroom_close_blinds


- alias: Open Living Space Blinds 30 minutes before Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.show_the_sunset'
      state: 'on'
  action:
    service: scene.turn_on
    entity_id:
    - scene.balcony_open
    - scene.living_room_open

#- alias: Living Space Blinds Closed at Night
#  trigger:
#    platform: template
#    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#  action:
#    service: scene.turn_on
#    entity_id:
#    - scene.balcony_blind
#    - scene.living_room_blind

- alias: Living Space Blinds Open in Morning
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.morning_blinds_open_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_blinds'
      state: 'on'
  action:
    - service: cover.open_cover
      entity_id:
        - cover.living_room_left_front
        - cover.living_room_middle_front
        - cover.living_room_right_front
        - cover.balcony_west_front

- alias: Calculate North Blinds Daily Times
  trigger:
    - platform: time
      at: "00:01:00"
    - platform: homeassistant
      event: start
  action:
    - delay: "00:00:10"
    - service: shell_command.calculate_blind_times

- alias: Close North Blinds in Morning Sun
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.north_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_north_blinds'
      state: 'on'
    - condition: template
      value_template: "{{ states('input_datetime.north_blinds_close_time') != '00:00:00' }}"
  action:
    - service: cover.close_cover
      entity_id:
        - cover.balcony_north_left_front
        - cover.balcony_north_right_front

- alias: Open North Blinds after Morning Sun Passes
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.north_blinds_open_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_north_blinds'
      state: 'on'
    - condition: template
      value_template: "{{ states('input_datetime.north_blinds_open_time') != '00:00:00' }}"
  action:
    - service: cover.open_cover
      entity_id:
        - cover.balcony_north_left_front
        - cover.balcony_north_right_front

- alias: Close West Blinds in Evening Sun
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.west_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_west_blinds'
      state: 'on'
    - condition: template
      value_template: "{{ states('input_datetime.west_blinds_close_time') != '00:00:00' }}"
  action:
    - service: cover.close_cover
      entity_id:
        - cover.living_room_left_front
        - cover.living_room_middle_front
        - cover.living_room_right_front

- alias: Open West Blinds after Evening Sun Passes
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.west_blinds_open_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'input_boolean.automatic_west_blinds'
      state: 'on'
    - condition: template
      value_template: "{{ states('input_datetime.west_blinds_open_time') != '00:00:00' }}"
  action:
    - service: cover.open_cover
      entity_id:
        - cover.living_room_left_front
        - cover.living_room_middle_front
        - cover.living_room_right_front

