- alias: Main Bedroom Blinds Closed
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'sensor.main_bedroom_night_blinds'
    state: 'Closed'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_closed

- alias: Main Bedroom Blinds Partly
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.bedroom_blinds_close_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'sensor.main_bedroom_night_blinds'
    state: 'Partly'
  action:
    service: scene.turn_on
    entity_id:  scene.main_bedroom_partly
