- alias: Doorbird Entry Ring
  trigger:
    platform: event
    event_type: doorbird_doorbird_entry_doorbell
  action:
    - service: camera.snapshot
#     last_ring not yet updated by the time it triggers
#     entity_id: camera.doorbird_entry_last_ring
      entity_id: camera.doorbird_entry_live
      data:
        filename: /config/www/doorbell/lastring.jpg
    - service: media_player.play_media
      entity_id: media_player.living_room_tv
      data:
        media_content_type: image/jpg
        media_content_id: 'https://amantes.duckdns.org:8123/local/doorbell/lastring.jpg'
    - service: media_player.play_media
      entity_id: media_player.balcony_display
      data:
        media_content_type: image/jpg
        media_content_id: 'https://amantes.duckdns.org:8123/local/doorbell/lastring.jpg'
    - service: media_player.play_media
      entity_id: media_player.living_room_mural
      data:
        media_content_type: image/jpg
        media_content_id: 'https://amantes.duckdns.org:8123/local/doorbell/lastring.jpg'
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data_template:
        message: "There is someone at the door."
