- alias: Fans on when Awake
  trigger:
    platform: state
    entity_id: input_select.mode_house
    to:
    - 'Awake'
    - 'Quiet'
  action:
    - service: switch.turn_on
      entity_id: switch.relay_qubino_main_bathroom_fan
    - service: switch.turn_on
      entity_id: switch.relay_qubino_guest_bathroom_fan

- alias: Fans off when Asleep
  trigger:
    platform: state
    entity_id: input_select.mode_house
    to:
    - 'Asleep'
  action:
    - service: switch.turn_off
      entity_id: switch.relay_qubino_main_bathroom_fan
    - service: switch.turn_off
      entity_id: switch.relay_qubino_guest_bathroom_fan
