- alias: Fans on when Awake
  trigger:
    platform: state
    entity_id: input_select.mode_house
    to: 'Awake'
  action:
    service: switch.turn_on
    entity_id: switch.relay_qubino_main_bathroom_fan
  action:
    service: switch.turn_on
    entity_id: switch.relay_qubino_guest_bathroom_fan

- alias: Fans off when Asleep/Quiet
  trigger:
    platform: state
    entity_id: input_select.mode_house
    to:
    - 'Asleep'
    - 'Quiet'
  action:
    service: switch.turn_off
    entity_id: switch.relay_qubino_main_bathroom_fan
  action:
    service: switch.turn_off
    entity_id: switch.relay_qubino_guest_bathroom_fan
