- alias: HomeSeer Balcony Light Single Up Light on
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.balcony_lights
- alias: HomeSeer Balcony Light Single Down Light off
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.balcony_lights
- alias: HomeSeer Balcony Light Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.balcony_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Balcony Light Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.balcony_lights
      color_name: white
      brightness_pct: 2
- alias: HomeSeer Balcony Light Triple Up All Lights on
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 1
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.all_lights_except_grow
- alias: HomeSeer Balcony Light Triple Down All Lights off
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_balcony
      scene_id: 2
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.all_lights_except_grow
