- alias: HomeSeer Guest Bedroom Light Single Up Light on
  id: hs-gber-single-up
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.guest_bedroom_lights
- alias: HomeSeer Guest Bedroom Light Single Down Light off
  id: hs-gber-single-down
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.guest_bedroom_lights
- alias: HomeSeer Guest Bedroom Light Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.guest_bedroom_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Guest Bedroom Light Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.guest_bedroom_lights
      color_name: white
      brightness_pct: 2
- alias: HomeSeer Guest Bedroom Light Triple Up Shades Up
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 1
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.27267
- alias: HomeSeer Guest Bedroom Light Triple Up Shades Down
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_guest_bedroom
      scene_id: 2
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.29558

