- alias: HomeSeer Hallway Light Single Up Light on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 10
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
    service_template: light.turn_on
    data:
      entity_id: light.hallway_lights

- alias: HomeSeer Hallway Light Single Down Light off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 10
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
    service_template: light.turn_off
    data:
      entity_id: light.hallway_lights

- alias: HomeSeer Hallway Light Double Up Light on/white/100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 10
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_lights
      brightness_pct: 100
      color_name: white

- alias: HomeSeer Hallway Light Double Down Light 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 10
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_lights
      color_name: white
      brightness_pct: 2

- alias: HomeSeer Hallway Triple Down Everything Off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 10
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: scene.turn_on
    entity_id:  scene.everything_off
