- alias: HomeSeer Hallway Light Single Up Light on
  id: hs-lrw-single-up
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_hallway
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_lights
- alias: HomeSeer Hallway Light Single Down Light off
  id: hs-lrw-single-down
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_hallway
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.hallway_lights
- alias: HomeSeer Hallway Light Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_hallway
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Hallway Light Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_hallway
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_lights
      color_name: white
      brightness_pct: 20
