- alias: HomeSeer Kitchen Light Single Up Light on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_lights

- alias: HomeSeer Kitchen Light Single Down Light off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_lights

- alias: HomeSeer Kitchen Light Double Up Light on/white/100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_lights
      brightness_pct: 100
      color_name: white

- alias: HomeSeer Kitchen Light Double Down Light 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_lights
      color_name: white
      brightness_pct: 2

- alias: HomeSeer Kitchen Light Triple Up Living Space on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.living_space_on

- alias: HomeSeer Kitchen Light Triple Down Living Space off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.living_space_off

- alias: HomeSeer Kitchen Light Quadruple Up Play This Quarter
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed4x
  condition: []
  action:
  - service: script.spotify_play_this_quarter
    data:
      device_name: "Living Room TV"

- alias: HomeSeer Kitchen Light Quadruple Down Play Upcoming Concerts
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 86
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed4x
  condition: []
  action:
  - service: script.spotify_play_upcoming_concerts
    data:
      device_name: "Living Room TV"
