- alias: HomeSeer Living Room Window Single Up Light on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 18
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights

- alias: HomeSeer Living Room Window Single Down Light off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 18
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.window_lights

- alias: HomeSeer Living Room Window Double Up Light on/white/100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 18
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      brightness_pct: 100
      color_name: white

- alias: HomeSeer Living Room Window Double Down Light 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 18
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      color_name: white
      brightness_pct: 2
