- alias: HomeSeer Living Room Window Single Up Light on
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_living_room_window
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights
- alias: HomeSeer Living Room Window Single Down Light off
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_living_room_window
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.window_lights
- alias: HomeSeer Living Room Window Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_living_room_window
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Living Room Window Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_living_room_window
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      color_name: white
      brightness_pct: 2
