- alias: HomeSeer Main Bathroom Sound Single Up Volume Up
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: media_player.volume_up
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Single Down Volume Down
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: media_player.volume_down
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Double Down Play/Pause Toggle
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Triple Up Play Bath
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bathroom
      volume_level: 0.10
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bathroom
      source: Bath
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Triple Down Toggle Fan
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: switch.toggle
    data:
      entity_id: switch.relay_qubino_main_bathroom_fan

- alias: HomeSeer Main Bathroom Sound Quadruple Up Play Wakey
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 77
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed4x
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bathroom
      volume_level: 0.10
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bathroom
      source: Wakey
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bathroom
