- alias: HomeSeer Main Bathroom Sound Single Up Volume Up
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: media_player.volume_up
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Single Down Volume Down
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: media_player.volume_down
    data:
      entity_id: media_player.main_bathroom
- alias: HomeSeer Main Bathroom Sound Double Down Play/Pause Toggle
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Triple Up Play Bath
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 1
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bathroom
      volume_level: 0.10
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bathroom
      source: Bath
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Triple Down Play Wakey
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 2
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bathroom
      volume_level: 0.10
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bathroom
      source: Wakey
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bathroom

- alias: HomeSeer Main Bathroom Sound Triple Down Toggle Fan
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_sound
      scene_id: 2
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: switch.toggle
    data:
      entity_id: switch.relay_qubino_main_bathroom_fan
