- alias: HomeSeer Main Bathroom Light Single Up Light on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights

- alias: HomeSeer Main Bathroom Light Single Down Light off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.main_bathroom_lights

- alias: HomeSeer Main Bathroom Light Double Up Light on/white/100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights
      brightness_pct: 100
      color_name: white

- alias: HomeSeer Main Bathroom Light Double Down Light 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights
      color_name: white
      brightness_pct: 2

- alias: HomeSeer Main Bathroom Light Triple Up Cycle Color Up
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.main_bathroom_lights
    data_template:
      hs_color:
        - "{{ (30 + (state_attr('light.main_bathroom_lights', 'hs_color')[0] or 0)) % 360 }}"
        - 100
      transition: 1

- alias: HomeSeer Main Bathroom Light Triple Down Cycle Color Down
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.main_bathroom_lights
    data_template:
      hs_color:
        - "{{ (-30 + (state_attr('light.main_bathroom_lights', 'hs_color')[0] or 0)) % 360 }}"
        - 100
      transition: 1
