- alias: HomeSeer Main Bedroom Light Single Up Light on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights

- alias: HomeSeer Main Bedroom Light Single Down Light off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.main_bedroom_lights

- alias: HomeSeer Main Bedroom Light Double Up Light on/white/100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights
      brightness_pct: 100
      color_name: white

- alias: HomeSeer Main Bedroom Light Double Down Light 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights
      color_name: white
      brightness_pct: 2

- alias: HomeSeer Main Bedroom Light Triple Up Left Shade Up
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_left_open

- alias: HomeSeer Main Bedroom Light Triple Down Left Shade Down
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_left_closed

- alias: HomeSeer Main Bedroom Light Quadruple Up Shades Up
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed4x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_open

- alias: HomeSeer Main Bedroom Light Quadruple Down Shades Partly
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed4x
  condition: []
  action:
  - service: scene.turn_on
    entity_id:  scene.main_bedroom_partly

- alias: HomeSeer Main Bedroom Light Quintuple Up Sleep
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 87
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed5x
  condition: []
  action:
  - service: scene.turn_on
    entity_id:  scene.main_bedroom_sleep
