- alias: HomeSeer Main Bedroom Light Single Up Light on
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bedroom
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights
- alias: HomeSeer Main Bedroom Light Single Down Light off
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bedroom
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.main_bedroom_lights
- alias: HomeSeer Main Bedroom Light Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bedroom
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Main Bedroom Light Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bedroom
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bedroom_lights
      color_name: white
      brightness_pct: 20
