- alias: HomeSeer Main Bathroom Light Single Up Light on
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 1
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights
- alias: HomeSeer Main Bathroom Light Single Down Light off
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 2
      scene_data: 7680
    platform: event
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.main_bathroom_lights
- alias: HomeSeer Main Bathroom Light Double Up Light on/white/100%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 1
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights
      brightness_pct: 100
      color_name: white
- alias: HomeSeer Main Bathroom Light Double Down Light 20%
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 2
      scene_data: 7860
    platform: event
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.main_bathroom_lights
      color_name: white
      brightness_pct: 2
- alias: HomeSeer Main Bathroom Light Triple Up Cycle Color Up
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 1
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.main_bathroom_lights
    data_template:
      hs_color:
        - "{{ (30 + (state_attr('light.main_bathroom_lights', 'hs_color')[0] or 0)) % 360 }}"
        - 100
      transition: 1

- alias: HomeSeer Main Bathroom Light Triple Down Cycle Color Down
  trigger:
  - event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.homeseer_hsws200_main_bathroom_light
      scene_id: 2
      scene_data: 7920
    platform: event
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.main_bathroom_lights
    data_template:
      hs_color:
        - "{{ (-30 + (state_attr('light.main_bathroom_lights', 'hs_color')[0] or 0)) % 360 }}"
        - 100
      transition: 1
