- alias: HomeSeer Main Bedroom North Triple Up Play Main Bedroom Wakey
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 22
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bedroom
      volume_level: 0.20
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bedroom
      source: Wakey
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bedroom

- alias: HomeSeer Main Bedroom North Triple Down Play/Pause Toggle
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 22
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.main_bedroom
