- alias: HomeSeer Main Bedroom South Triple Up Play Main Bedroom Wakey
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 21
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed3x
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.main_bedroom
      volume_level: 0.20
  - service: media_player.select_source
    data:
      entity_id: media_player.main_bedroom
      source: Wakey
  - service: media_player.media_play
    data:
      entity_id: media_player.main_bedroom

- alias: HomeSeer Main Bedroom South Triple Down Play/Pause Toggle
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 21
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed3x
  condition: []
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.main_bedroom

- id: homeseer_main_bedroom_south_light_longpress_dimming
  alias: HomeSeer Main Bedroom South Light Long-Press Dimming
  use_blueprint:
    path: homeseer_longpress_dimming.yaml
    input:
      switch_node_id: 21
      target_light: light.main_bedroom_wall_south
