- alias: Remotec-4 - 5 Living Room FIOS
  trigger:
  - event_data:
      entity_id: zwave.switch_remotec_4
      scene_data: 0
      scene_id: 5
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - service: media_player.turn_on
    entity_id: media_player.samsung_tv
  - service: scene.turn_on
    entity_id: scene.living_tv_fios

- alias: Remotec-4 - 6 Living Room Stadia
  trigger:
  - event_data:
      entity_id: zwave.switch_remotec_4
      scene_data: 0
      scene_id: 6
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.living_tv_stadia

- alias: Remotec-4 - 7 Living Room PS3
  trigger:
  - event_data:
      entity_id: zwave.switch_remotec_4
      scene_data: 0
      scene_id: 7
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.living_tv_ps3

- alias: Remotec-4 - 8 Living Room PS4
  trigger:
  - event_data:
      entity_id: zwave.switch_remotec_4
      scene_data: 0
      scene_id: 8
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.living_tv_ps4
