- id: '1540767017204'
  alias: Remotec-1 1 LIFX Main Bedroom Toggle
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '001'
      value: KeyPressed
  condition: []
  action:
  - data:
      entity_id: light.main_bedroom_lights
    service: light.toggle

- id: '1540677632635'
  alias: Remotec-1 2 LIFX Bedroom Phoenix Sleepy
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '002'
      value: KeyPressed
  condition: []
  action:
  - data:
      entity_id: light.main_bedroom_lights
      color_name: white
      brightness_pct: 5
    service: light.turn_on

- id: '1540677631635'
  alias: Remotec-1 3 LIFX Bedroom Half
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '003'
      value: KeyPressed
  condition: []
  action:
  - data:
      entity_id: light.main_bedroom_lights
      color_name: white
      brightness_pct: 50
    service: light.turn_on

- id: '8540677632635'
  alias: Remotec-1 3 Double LIFX Bedroom Bright
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '003'
      value: KeyPressed2X
  condition: []
  action:
  - data:
      entity_id: light.main_bedroom_lights
      color_name: white
      brightness_pct: 100
    service: light.turn_on

- alias: Remotec-1 4 Bed Flat
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '004'
      value: KeyPressed
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed_lift
      option: Flat
  - service: input_select.select_option
    data:
      entity_id: input_select.bed_massage
      option: Stop

- alias: Remotec-1 4 Double Bed Lift
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '004'
      value: KeyPressed2X
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed_lift
      option: Memory 1

- id: '5540767017205'
  alias: Remotec-1 5 Projector FIOS Quiet
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '005'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_fios_quiet
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- id: '3540677632631'
  alias: Remotec-1 6 Projector Stadia Quiet
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '006'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_stadia_quiet
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- id: '2440677632691'
  alias: Remotec-1 7 Projector PS3 Quiet
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '007'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_ps3_quiet
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- id: '2440677632692'
  alias: Remotec-1 8 Projector PS4 Quiet
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '008'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_ps4_quiet
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Remotec-1 5 Double Projector FIOS Loud
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '005'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_fios_loud
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Remotec-1 6 Double Projector Stadia Loud
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '006'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_stadia_loud
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Remotec-1 7 Double Projector PS3 Loud
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '007'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_ps3_loud
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

- alias: Remotec-1 8 Double Projector PS4 Loud
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      command_class_name: Central Scene
      property: scene
      property_key: '008'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.main_bedroom_projector_ps4_loud
  - service: scene.turn_on
    entity_id: scene.main_bedroom_closed

