- alias: Remotec-3 1 Balcony On
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '001'
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.balcony_lights

- alias: Remotec-3 1 Double Balcony Off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '001'
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.balcony_lights

- alias: Remotec-3 2 Balcony 100%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '002'
      value: KeyPressed
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.balcony_lights
      brightness_pct: 100
      color_name: white

- alias: Remotec-3 2 Double Balcony 20%
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '002'
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.balcony_lights
      brightness_pct: 20
      color_name: white


- alias: Remotec-3 3 Shades Open
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '003'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_open

- alias: Remotec-3 3 Shades Double Blind
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '003'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_blind

- alias: Remotec-3 4 Walking Pad On
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '004'
      value: KeyPressed
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.walking_pad

- alias: Remotec-3 4 Double Walking Pad Off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '004'
      value: KeyPressed2x
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.walking_pad

- alias: Remotec-3 - 5 Double Balcony Laptop
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '005'
      value: KeyPressed2x
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_laptop

- alias: Remotec-3 - 5 Balcony FIOS
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '005'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_fios

- alias: Remotec-3 - 6 Balcony Stadia
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '006'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_stadia

- alias: Remotec-3 - 7 Balcony PS3
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '007'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_playstation_3

- alias: Remotec-3 - 8 Balcony PS4
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '008'
      value: KeyPressed
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.balcony_playstation_4

- alias: Remotec-3 - 7 Double Balcony Play This Quarter
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '007'
      value: KeyPressed2x
  condition: []
  action:
  - service: script.spotify_play_this_quarter
    data:
      device_name: "Living Room TV"

- alias: Remotec-3 - 8 Double Balcony Play Upcoming Concerts
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      command_class_name: Central Scene
      property: scene
      property_key: '008'
      value: KeyPressed2x
  condition: []
  action:
  - service: script.spotify_play_upcoming_concerts
    data:
      device_name: "Living Room TV"
