- alias: Remotec-4 - 5 Living Room FIOS
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 56
      command_class_name: Central Scene
      property: scene
      property_key: '005'
      value: KeyPressed
  action:
  - service: media_player.turn_on
    entity_id: media_player.samsung_tv
  - service: scene.turn_on
    entity_id: scene.living_room_fios

- alias: Remotec-4 - 6 Living Room Stadia
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 56
      command_class_name: Central Scene
      property: scene
      property_key: '006'
      value: KeyPressed
  action:
  - service: scene.turn_on
    entity_id: scene.living_room_stadia

- alias: Remotec-4 - 7 Living Room PS3
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 56
      command_class_name: Central Scene
      property: scene
      property_key: '007'
      value: KeyPressed
  action:
  - service: scene.turn_on
    entity_id: scene.living_room_playstation_3

- alias: Remotec-4 - 8 Living Room PS4
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 56
      command_class_name: Central Scene
      property: scene
      property_key: '008'
      value: KeyPressed
  action:
  - service: scene.turn_on
    entity_id: scene.living_room_playstation_4
