- alias: Calendar School Announce
  trigger:
    platform: template
    value_template: "{{ as_timestamp(now()) | int == strptime(states.calendar.school_phoenix.attributes.start_time, '%Y-%m-%d %H:%M:%S').timestamp() | int - 300}}"
  condition:
#   - condition: state
#     entity_id: calendar.school_phoenix
#     state: School Phoenix
    - condition: state
      entity_id: 'input_boolean.phoenix_class_announcements'
      state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: Turn on class announcements again on Sunday
  id: school-turn-on
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().weekday() == 6 and now().month not in [7, 8] }}'
  action:
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.phoenix_class_announcements
