- alias: School 1
  id: school-1
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_1', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.phoenix_class_announcements'
      state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: School 2
  id: school-2
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_2', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.phoenix_class_announcements'
      state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: School 3
  id: school-3
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_3', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.phoenix_class_announcements'
      state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: School 4
  id: school-4
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_4', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.phoenix_class_announcements'
      state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: Turn on class announcements again on Sunday
  id: school-turn-on
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().weekday() == 6 and now().month not in [7, 8] }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Thanksgiving
