- alias: School 1
  id: school-1
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_1', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: School 2
  id: school-2
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_2', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school

- alias: School 3
  id: school-3
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.school_3', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: script.repeat_message
    data:
      repeat_message: Phoenix it is time for school
