- alias: Seasonal Catalunya
  id: seasonal-catalunya
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "09-11" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Catalunya

- alias: Seasonal Spain
  id: seasonal-spain
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "10-12" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Spain

- alias: Seasonal Halloween
  id: seasonal-halloween
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "10-31" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Halloween

- alias: Seasonal Thanksgiving
  id: seasonal-thanksgiving
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().weekday() == 3 and now().day > 21 and now().day < 29 and now().month == 11 }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Thanksgiving

- alias: Seasonal Sinterklaas
  id: seasonal-sinterklaas
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "11-30" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Sinterklaas

- alias: Seasonal Christmas
  id: seasonal-christmas
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "12-24" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Christmas


- alias: Seasonal Birthday Phoenix
  id: seasonal-birthday-phoenix
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "01-05" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Birthday

- alias: Seasonal Birthday Thomas
  id: seasonal-birthday-thomas
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "07-07" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Birthday

- alias: Seasonal Birthday Natalia
  id: seasonal-birthday-natalia
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "03-11" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Birthday

- alias: Seasonal Anthem Australia
  id: seasonal-anthem-australia
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "01-26" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Australia

- alias: Seasonal Anthem Belgium
  id: seasonal-anthem-belgium
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "07-21" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Belgium

- alias: Seasonal Anthem Vlaanderen
  id: seasonal-anthem-vlaanderen
  trigger:
    platform: time
    at: "04:00:00"
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "07-11" }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mode_seasonal
      option: Vlaanderen

- alias: Thanksgiving Open
  id: thanksgiving-open
  trigger:
  - entity_id: binary_sensor.door_gbar
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_gber
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.mode_seasonal
    state: 'Thanksgiving'
  - condition: state
    entity_id: input_select.mode_house
    state: 'Awake'
  action:
    - service: script.turn_on
      entity_id: script.thanksgiving_gobble_kitchen

# Meural source
- alias: Meural Halloween
  id: meural-halloween
  trigger:
  - entity_id: input_select.mode_seasonal
    platform: state
    to: 'Halloween'
  action:
    service: media_player.select_source
    data:
      source: Halloween
    target:
      entity_id: media_player.living_room_mural

- alias: Meural Thanksgiving
  id: meural-thanksgiving
  trigger:
  - entity_id: input_select.mode_seasonal
    platform: state
    to: 'Thanksgiving'
  action:
    service: media_player.select_source
    data:
      source: Thanksgiving
    target:
      entity_id: media_player.living_room_mural


- alias: Meural Sinterklaas
  id: meural-sinterklaas
  trigger:
  - entity_id: input_select.mode_seasonal
    platform: state
    to: 'Sinterklaas'
  action:
    service: media_player.select_source
    data:
      source: Sinterklaas
    target:
      entity_id: media_player.living_room_mural

- alias: Meural Off
  id: meural-off
  trigger:
  - entity_id: input_select.mode_seasonal
    platform: state
    to: 'False'
  action:
    service: media_player.select_source
    data:
      source: 'Display Portrait'
    target:
      entity_id: media_player.living_room_mural
